# Generated by Django 5.0.4 on 2024-04-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=240)),
                ("image", models.ImageField(upload_to="users/")),
                ("star", models.IntegerField()),
                ("feedback", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="specialist",
            name="specialization",
            field=models.CharField(
                choices=[("YURIST", "Yurist"), ("SHIPAKER", "Shipaker")], max_length=20
            ),
        ),
    ]
