# Generated by Django 5.0.4 on 2024-04-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0002_userbase_alter_specialist_specialization"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Analgin", max_length=200)),
                ("price", models.IntegerField(default=0)),
                ("image", models.ImageField(upload_to="aptekars")),
            ],
        ),
    ]
